<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="vindi_subscription_items" data-form-part="subscription_form" id="vindi_subscription_items" value=""  />
<script type="text/x-magento-init">
    {
        "*": {
            "Vindi_Payment/js/assign-subscription-items": {
                "selectedItems":  <?= /* @escapeNotVerified */ $block->getSubscriptionItemsJson() ?>,
            "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
    }
}
}
</script>
<script>
    require('mage/apply/main').apply();
</script>
