<?php

/**
 * @var \Vindi\Payment\Block\Custom\PaymentLink $block
 */

$paymentLink = $block->getPaymentLink();

?>
<?php if ($paymentLink): ?>
    <?php
    $paymentMethodCode = str_replace('vindi_vr_', '', $paymentLink->getVindiPaymentMethod());
    $order = $block->getOrder();
    $customer = $block->getCustomerById($order->getCustomerId());
    $billingAddress = $order->getBillingAddress();
    $taxvat = $customer ? $customer->getTaxvat() : '';
    $instructions = $block->getInstructions();
    $isOrderCustomer = $block->isCustomerOrderOwner();
    $paymentProfiles = $block->getPaymentProfiles();
    ?>
    <div class="vindi-link-container">
        <div class="customer-data">
            <div class="customer-information">
                <h1><?= __('Customer Information') ?></h1>
                <div>
                    <span><strong><?= __('Name: ') ?></strong><?= htmlspecialchars($order->getCustomerFirstname(), ENT_QUOTES, 'UTF-8') ?></span>
                    <span><strong><?= __('Email: ') ?></strong><?= htmlspecialchars($order->getCustomerEmail(), ENT_QUOTES, 'UTF-8') ?></span>
                    <span><strong><?= __('Phone: ') ?></strong><?= htmlspecialchars($billingAddress->getTelephone(), ENT_QUOTES, 'UTF-8') ?></span>
                </div>
            </div>
            <br>
            <div class="customer-shipping">
                <h1><?= __('Shipping Data') ?></h1>
                <div>
                    <?php
                    $streets = [
                        __('Street: '),
                        __('Number: '),
                        __('Complement: '),
                        __('Neighborhood: ')
                    ];
                    ?>
                    <?php foreach ($streets as $key => $street): ?>
                        <?php if (!empty($billingAddress->getStreet()[$key])): ?>
                            <span><strong><?= $street ?></strong><?= htmlspecialchars($billingAddress->getStreet()[$key], ENT_QUOTES, 'UTF-8') ?></span>
                        <?php endif; ?>
                    <?php endforeach ?>
                    <span><strong><?= __('City: ') ?></strong><?= htmlspecialchars($billingAddress->getCity(), ENT_QUOTES, 'UTF-8') ?></span>
                    <span><strong><?= __('State: ') ?></strong><?= htmlspecialchars($billingAddress->getRegionCode(), ENT_QUOTES, 'UTF-8') ?></span>
                    <span><strong><?= __('Phone: ') ?></strong><?= htmlspecialchars($billingAddress->getTelephone(), ENT_QUOTES, 'UTF-8') ?></span>
                </div>
            </div>
        </div>

        <div class="payment-container">
            <h1><?= __('Payment Method') ?></h1>
            <div class="border rounded-md">
                <?php if ($paymentMethodCode == 'vindi_pix' || $paymentMethodCode == 'vindi_bankslippix'): ?>
                    <h3 class="text-lg font-semibold mb-4">Pix</h3>
                    <div class="flex justify-center mb-4">
                        <img src="<?= $block->getViewFileUrl('Vindi_Payment::images/payment_methods/pix.png') ?>" alt="Pix Logo" class="h-12">
                    </div>
                    <p class="text-center text-gray-500"><?= __('You will receive the QRCode to make the payment after completing the order') ?></p>
                <?php endif; ?>

                <?php if ($paymentMethodCode == 'vindi_bankslip' || $paymentMethodCode == 'vindi_bankslippix'): ?>
                    <h3 class="text-lg font-semibold mb-4"><?= __('Bankslip') ?></h3>
                    <div class="flex justify-center mb-4">
                        <img src="<?= $block->getViewFileUrl('Vindi_Payment::images/payment_methods/bankslip.png') ?>" alt="Bankslip Logo" class="h-12">
                    </div>
                    <p class="text-center text-gray-500"><?= __('You will receive the bankslip to make the payment after completing the order') ?></p>
                <?php endif; ?>


                <?php if ($paymentMethodCode == 'vindi'): ?>
                    <h3 class="text-lg font-semibold mb-4"><?= __('Credit Card') ?></h3>
                <?php if ($isOrderCustomer): ?>
                    <div class="field number required">
                        <label class="label" for="vindi_cc_number">
                            <span><?= __('Your saved cards') ?></span>
                        </label>
                        <div class="control">
                            <select name="payment[payment_profile]" class="input-text select" id="vindi_cc_number" data-container="vindi-cc-number" onchange="toggleCardForm(this)">
                                <option value=""><?= __('New Card') ?></option>
                                <?php foreach ($paymentProfiles as $profile): ?>
                                    <option value="<?= $profile['value'] ?>"><?= $profile['text'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                <?php endif; ?>

                    <div id="credit-card-form">
                        <div class="form-group">
                            <input type="text" id="cc_number" class="form-input" placeholder="<?= __('Card Number') ?>">
                        </div>

                        <div class="form-group">
                            <input type="text" id="cc_name" class="form-input" placeholder="<?= __('Name on Card') ?>">
                        </div>

                        <div class="form-row">
                            <div class="form-group col-half">
                                <input type="text" id="cc_expiry" class="form-input" placeholder="<?= __('MM/YY') ?>" maxlength="5">
                            </div>
                            <div class="form-group col-half">
                                <input type="text" id="cc_cvv" class="form-input" placeholder="<?= __('CVV') ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <select id="cc_installments" class="form-input">
                                <option value="" disabled selected><?= __('Installments') ?></option>
                            </select>
                        </div>
                    </div>

                    <div id="installments-only" style="display:none;">
                        <div class="form-group">
                            <select id="cc_installments_saved" class="form-input">
                                <option value="" disabled selected><?= __('Installments') ?></option>
                            </select>
                        </div>
                    </div>

                    <div class="credit-card-icons">
                        <img src="<?= $block->getViewFileUrl('Vindi_Payment::images/cc/vi.png') ?>" alt="Visa" class="h-6 cc-icon" id="cc-icon-visa">
                        <img src="<?= $block->getViewFileUrl('Vindi_Payment::images/cc/mc.png') ?>" alt="MasterCard" class="h-6 cc-icon" id="cc-icon-mastercard">
                        <img src="<?= $block->getViewFileUrl('Vindi_Payment::images/cc/ae.png') ?>" alt="American Express" class="h-6 cc-icon" id="cc-icon-american-express">
                        <img src="<?= $block->getViewFileUrl('Vindi_Payment::images/cc/elo.png') ?>" alt="Elo" class="h-6 cc-icon" id="cc-icon-elo">
                    </div>
                    <input type="hidden" id="cc_type" name="cc_type" value="">

                    <script>
                        function toggleCardForm(select) {
                            const ccForm = document.getElementById('credit-card-form');
                            const installmentsOnly = document.getElementById('installments-only');

                            if (select.value === "") {
                                ccForm.style.display = 'block';
                                installmentsOnly.style.display = 'none';
                                populateInstallments('cc_installments');
                            } else {
                                ccForm.style.display = 'none';
                                installmentsOnly.style.display = 'block';
                                populateInstallments('cc_installments_saved');
                            }
                        }

                        function populateInstallments(selectId) {
                            const selectInstallments = document.getElementById(selectId);
                            const grandTotal = <?= $order->getGrandTotal() ?>;
                            const minInstallmentsValue = 10;
                            const maxInstallments = 12;

                            if (selectInstallments) {
                                selectInstallments.innerHTML = '<option value="" disabled selected><?= $block->getTranslation("Installments") ?></option>';

                                for (let i = 1; i <= maxInstallments; i++) {
                                    let installmentValue = (grandTotal / i).toFixed(2).replace('.', ',');
                                    if (installmentValue < minInstallmentsValue) break;
                                    let option = document.createElement('option');
                                    option.value = i;
                                    option.text = `${i}x <?= $block->getTranslation("of") . ' ' . $block->getCurrencySymbol() ?> ${installmentValue}`;
                                    selectInstallments.appendChild(option);
                                }
                            }
                        }
                    </script>
                <?php endif; ?>

                <div class="form-group">
                    <label><?= __('CPF/CNPJ:') ?></label>
                    <input type="text" id="taxvat" class="form-input" placeholder="<?= __('Responsible CPF') ?>" value="<?= htmlspecialchars($taxvat, ENT_QUOTES, 'UTF-8') ?>">
                </div>
            </div>
        </div>

        <!-- Order Summary Section -->
        <div class="order-summary">
            <div class="block-title">
                <strong><?= __('Order Summary') ?></strong>
            </div>
            <div class="block-content">
                <table class="data table table-totals">
                    <tbody>
                    <tr class="totals sub">
                        <th class="mark" scope="row"><?= __('Cart Subtotal') ?></th>
                        <td class="amount"><?= $block->getFormattedPrice($order->getSubtotal()) ?></td>
                    </tr>

                    <?php if ($order->getDiscountAmount()): ?>
                        <tr class="totals discount">
                            <th class="mark" scope="row"><?= __('Discount') ?></th>
                            <td class="amount"><?= $block->getFormattedPrice($order->getDiscountAmount()) ?></td>
                        </tr>
                    <?php endif; ?>

                    <tr class="totals shipping excl">
                        <th class="mark" scope="row"><?= __('Shipping') ?></th>
                        <td class="amount"><?= $block->getFormattedPrice($order->getShippingAmount()) ?></td>
                    </tr>
                    <tr class="grand totals">
                        <th class="mark" scope="row"><strong><?= __('Order Total') ?></strong></th>
                        <td class="amount"><strong><?= $block->getFormattedPrice($order->getGrandTotal()) ?></strong></td>
                    </tr>
                    </tbody>
                </table>
                <div class="items-in-cart">
                    <strong><?= $order->getTotalItemCount() . ' ' . __('Item(s) in Cart') ?></strong>
                    <div class="items">
                        <?php foreach ($order->getItems() as $item): ?>
                            <div class="item">
                                <div class="item-info">
                                    <div class="product-image">
                                        <img src="<?= $block->getImageUrl($item->getProductId()) ?>" alt="<?= htmlspecialchars($item->getName(), ENT_QUOTES, 'UTF-8') ?>" width="80" />
                                    </div>
                                    <div class="product-details">
                                        <strong><?= htmlspecialchars($item->getName(), ENT_QUOTES, 'UTF-8') ?></strong>
                                        <div class="qty-price">
                                            <span><?= __('Qty: ') . intval($item->getQtyOrdered()) ?></span>
                                            <span><?= $block->getFormattedPrice($item->getPrice()) ?></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button class="action primary checkout"
                            type="button"
                            onclick="sendPayment()"
                            title="<?= __('Place Order') ?>">
                        <span><?= __('Place Order') ?></span>
                    </button>
                </div>
            </div>
        </div>

        <div id="loading-overlay">
            <div class="loader"></div>
        </div>
        <div id="warning-message" class="warning-message"></div>

        <script>
            function sendPayment() {
                if (!validateCreditCardForm()) {
                    return;
                }

                var xhr = new XMLHttpRequest();
                var url = '<?= $block->escapeUrl($block->getUrl('vindi_vr/checkout/sendtransaction')) ?>';
                var orderId = '<?= $order->getId() ?>';
                var formKey = '<?= $block->getFormKey() ?>';
                var methodCode = '<?= $paymentMethodCode ?>';
                var taxvat = document.getElementById('taxvat').value.trim();
                var paymentData;

                if (methodCode === 'vindi') {
                    var paymentProfile = document.getElementById('vindi_cc_number')?.value || "";
                    if (paymentProfile === "") {
                        var ccNumber = document.getElementById('cc_number').value.replace(/\s+/g, '');
                        var ccName = document.getElementById('cc_name').value.trim();
                        var ccExpiry = document.getElementById('cc_expiry').value.trim();
                        var ccCvv = document.getElementById('cc_cvv').value.trim();
                        var ccInstallments = document.getElementById('cc_installments').value;
                        var ccType = document.getElementById('cc_type').value;

                        var ccExpMonth = '';
                        var ccExpYear = '';
                        if (ccExpiry) {
                            var ccExpDateFull = ccExpiry.split('/');
                            ccExpMonth = ccExpDateFull[0];
                            ccExpYear = ccExpDateFull[1];
                        }

                        var ccLast4 = ccNumber.slice(-4);

                        paymentData = {
                            order_id: orderId,
                            payment_data: {
                                method: methodCode,
                                additional_data: {
                                    taxvat: taxvat,
                                    cc_cid: ccCvv,
                                    cc_type: ccType,
                                    cc_exp_month: ccExpMonth,
                                    cc_exp_year: ccExpYear.length === 4 ? ccExpYear : '20' + ccExpYear,
                                    cc_number: ccNumber,
                                    cc_owner: ccName,
                                    installments: ccInstallments,
                                    cc_last_4: ccLast4
                                }
                            },
                            form_key: formKey
                        };
                    } else {
                        var ccInstallmentsSaved = document.getElementById('cc_installments_saved').value;
                        paymentData = {
                            order_id: orderId,
                            payment_data: {
                                method: methodCode,
                                additional_data: {
                                    taxvat: taxvat,
                                    payment_profile: paymentProfile,
                                    installments: ccInstallmentsSaved
                                }
                            },
                            form_key: formKey
                        };
                    }
                } else {
                    paymentData = {
                        order_id: orderId,
                        payment_data: {
                            method: methodCode,
                            additional_data: {
                                taxvat: taxvat
                            }
                        },
                        form_key: formKey
                    };
                }

                document.getElementById('loading-overlay').style.display = 'flex';

                xhr.open('POST', url, true);
                xhr.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
                xhr.onreadystatechange = function () {
                    document.getElementById('loading-overlay').style.display = 'none';
                    if (xhr.readyState === 4) {
                        if (xhr.status === 200) {
                            var response = JSON.parse(xhr.responseText);
                            if (response.success) {
                                window.paymentLinkSuccess = true;
                                window.location.href = '<?= $block->escapeUrl($block->getUrl('vindi_vr/checkout/success')) ?>?order_id=' + orderId;
                            } else {
                                displayWarningMessage('<?= $block->getTranslation("Something went wrong. Please try again.") ?>');
                            }
                        } else {
                            displayWarningMessage('<?= $block->getTranslation("Something went wrong. Please try again.") ?>');
                        }
                    }
                };
                xhr.send(JSON.stringify(paymentData));
            }

            function getCardType(number) {
                const cardTypes = {
                    visa: /^4[0-9]{12}(?:[0-9]{3})?$/,
                    mastercard: /^(?:5[1-5][0-9]{14}|2[2-7][0-9]{14})$/,
                    'american-express': /^3[47][0-9]{13}$/,
                    elo: /^(4011(78|79)|4312(74|76)|4514(16|17)|5041(75|76)|5066|5090|6277|6362)[0-9]{0,12}$/
                };

                for (const type in cardTypes) {
                    if (cardTypes[type].test(number)) {
                        console.log('Detected Card Type:', type);
                        return type.toUpperCase();
                    }
                }
                return null;
            }

            document.addEventListener("DOMContentLoaded", function () {
                const ccExpiry = document.getElementById('cc_expiry');
                if (ccExpiry) {
                    ccExpiry.addEventListener('input', function (e) {
                        e.target.value = e.target.value.replace(
                            /^([1-9]\/|[2-9])$/g, '0$1/'
                        ).replace(
                            /^(0[1-9]|1[0-2])$/g, '$1/'
                        ).replace(
                            /^([0-1])([3-9])$/g, '0$1/$2'
                        ).replace(
                            /^(0?[1-9]|1[0-2])([0-9]{2})$/g, '$1/$2'
                        ).replace(
                            /^([0]+)\/|[0]+$/g, '0'
                        ).replace(
                            /[^\d\/]|^[\/]*$/g, ''
                        ).replace(
                            /\/\//g, '/'
                        );

                        if (e.target.value.length > 5) {
                            e.target.value = e.target.value.slice(0, 5);
                        }
                    });
                }

                const ccNumber = document.getElementById('cc_number');
                if (ccNumber) {
                    ccNumber.addEventListener('input', function () {
                        const value = ccNumber.value.replace(/\s+/g, '');
                        let cardType = getCardType(value);

                        document.querySelectorAll('.cc-icon').forEach(icon => {
                            icon.classList.remove('highlighted');
                        });

                        if (cardType) {
                            const icon = document.getElementById(`cc-icon-${cardType.toLowerCase()}`);
                            if (icon) {
                                icon.classList.add('highlighted');
                            }
                            document.getElementById('cc_type').value = cardType.toLowerCase().replace(/-/g, '_');
                        }

                        applyCardNumberMask(cardType);
                        applyCvvMask(cardType);
                    });
                }

                function applyCardNumberMask(cardType) {
                    const ccNumber = document.getElementById('cc_number');

                    if (ccNumber) {
                        if (cardType === 'AMERICAN-EXPRESS') {
                            ccNumber.maxLength = 17;
                            ccNumber.placeholder = 'XXXX XXXXXX XXXXX';
                            ccNumber.addEventListener('input', function () {
                                ccNumber.value = ccNumber.value.replace(/^(\d{4})(\d{6})(\d{5}).*/, '$1 $2 $3');
                            });
                        } else if (cardType) {
                            ccNumber.maxLength = 19;
                            ccNumber.placeholder = 'XXXX XXXX XXXX XXXX';
                            ccNumber.addEventListener('input', function () {
                                ccNumber.value = ccNumber.value.replace(/^(\d{4})(\d{4})(\d{4})(\d{4}).*/, '$1 $2 $3 $4');
                            });
                        } else {
                            ccNumber.maxLength = 19;
                            ccNumber.placeholder = '<?= $block->getTranslation("Card Number") ?>';
                            ccNumber.addEventListener('input', function () {
                                ccNumber.value = ccNumber.value.replace(/\s/g, '').replace(/(\d{4})/g, '$1 ').trim();
                            });
                        }
                    }
                }

                function applyCvvMask(cardType) {
                    const ccCvv = document.getElementById('cc_cvv');
                    if (ccCvv) {
                        if (cardType === 'AMERICAN-EXPRESS') {
                            ccCvv.maxLength = 4;
                            ccCvv.placeholder = '<?= $block->getTranslation("XXXX") ?>';
                        } else if (cardType) {
                            ccCvv.maxLength = 3;
                            ccCvv.placeholder = '<?= $block->getTranslation("XXX") ?>';
                        } else {
                            ccCvv.maxLength = 4;
                            ccCvv.placeholder = '<?= $block->getTranslation("CVV") ?>';
                        }
                    }
                }

                populateInstallments('cc_installments');
                populateInstallments('cc_installments_saved');
            });

            function validateCreditCardForm() {
                var ccNumber = document.getElementById('cc_number')?.value.trim();
                var ccName = document.getElementById('cc_name')?.value.trim();
                var ccExpiry = document.getElementById('cc_expiry')?.value.trim();
                var ccCvv = document.getElementById('cc_cvv')?.value.trim();
                var ccInstallments = document.getElementById('cc_installments')?.value;
                var taxvat = document.getElementById('taxvat')?.value.trim();

                var errors = [];

                if ('<?= $paymentMethodCode ?>' === 'vindi') {
                    if (!document.getElementById('vindi_cc_number')?.value) {
                        if (!ccNumber) {
                            errors.push('<?= $block->getTranslation("Card Number") ?>');
                        }
                        if (!ccName) {
                            errors.push('<?= $block->getTranslation("Name on Card") ?>');
                        }
                        if (!ccExpiry) {
                            errors.push('<?= $block->getTranslation("Expiry Date") ?>');
                        }
                        if (!ccCvv) {
                            errors.push('<?= $block->getTranslation("CVV") ?>');
                        }
                        if (!ccInstallments) {
                            errors.push('<?= $block->getTranslation("Installments") ?>');
                        }
                    }
                }

                if (!taxvat) {
                    errors.push('<?= $block->getTranslation("Responsible CPF") ?>');
                }

                if (errors.length > 0) {
                    alert('<?= $block->getTranslation("Please fill in the following fields: ") ?>' + errors.join(', '));
                    return false;
                }

                return true;
            }

            function displayWarningMessage(message) {
                var warningMessageDiv = document.getElementById('warning-message');
                warningMessageDiv.innerText = message;
                warningMessageDiv.style.display = 'block';
            }
        </script>
    </div>
<?php endif; ?>
