<?php

use Vindi\Payment\Block\Subscription\Details;
use Vindi\Payment\Model\Payment\PaymentMethod;

/** @var Details $block */

$subscription = $block->getSubscription();
?>
<h2><?= __('Subscription: #') . $subscription->getId() ?></h2>

<div class="back-button-container">
    <button type="button" id="custom-back-button" class="back-button"><?= __('< Back') ?></button>
</div>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Details') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                    <tr>
                        <th><?= __('Customer') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getCustomerName()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Status') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getStatus())) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Since') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getStartAt()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Plan') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getPlanName()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Periodicity') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getPlanCycle())) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Duration') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getPlanDuration())) ?></strong></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Billing') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody>
                    <tr>
                        <th><?= __('Next Billing') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getNextBillingAt()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Billing') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getBillingTrigger())) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Payment Method') ?></th>
                        <td>
                            <strong><?= $block->getPaymentMethodLabel($subscription->getPaymentMethod()) ?></strong><br>
                            <?php if ($subscription->getData('payment_method') != PaymentMethod::CREDIT_CARD && $subscription->getData('payment_method') != PaymentMethod::DEBIT_CARD) : ?>
                                <div class="non-card-method-image"><?= $block->getPaymentMethodImage() ?></div>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= __('Duration') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getPlanDuration())) ?></strong></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Products') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th class="col-product"><span><?= __('Product') ?></span></th>
                <th class="col-qty"><span><?= __('Quantity') ?></span></th>
                <th class="col-cycle"><span><?= __('Duration') ?></span></th>
                <th class="col-price"><span><?= __('Price') ?></span></th>
                <th class="col-status last"><span><?= __('Status') ?></span></th>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($block->getProducts())): ?>
                <?php foreach($block->getProducts() as $key => $product): ?>
                    <tr class="<?php echo ($key % 2) ? 'even' : 'odd'?>">
                        <td class="col-product">
                            <div class="option-value"><?php echo $block->escapeHtml($product['product']['name']) ?></div>
                        </td>
                        <td class="col-qty">
                            <div class="option-value"><?php echo $block->escapeHtml($product['quantity']) ?></div>
                        </td>
                        <td class="col-cycle">
                            <div class="option-value"><?php echo $block->escapeHtml($block->getCycleLabel($product['cycles'], $product['uses'])) ?></div>
                        </td>
                        <td class="col-price">
                            <div class="price-excl-tax">
                                <div class="price"><?php echo $block->escapeHtml($product['pricing_schema']['short_format']) ?></div>
                            </div>
                        </td>
                        <td class="col-status last">
                            <div class="option-value"><?php echo $block->escapeHtml(__($product['status'])) ?></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="5" class="empty"><span><?= __('No products found.') ?></span></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Periods') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th class="col-product"><span><?= __('Period') ?></span></th>
                <th class="col-billing_at"><span><?= __('Billing') ?></span></th>
                <th class="col-cycle last"><span><?= __('Cycle') ?></span></th>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($block->getPeriods())): ?>
                <?php foreach($block->getPeriods() as $key => $period): ?>
                    <tr class="<?php echo ($key % 2) ? 'even' : 'odd'?>">
                        <td class="col-product">
                            <div class="option-value"><?php echo $block->escapeHtml($block->dateFormat($period['start_at'])) ?> - <?php echo $block->escapeHtml($block->dateFormat($period['end_at'])) ?></div>
                        </td>
                        <td class="col-billing_at">
                            <div class="option-value"><?php echo $block->escapeHtml($block->dateFormat($period['billing_at'])) ?></div>
                        </td>
                        <td class="col-cycle">
                            <div class="option-value"><?php echo $block->escapeHtml($period['cycle']) ?></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="empty"><span><?= __('No periods found.') ?></span></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Discounts') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th class="col-product"><span><?= __('Product') ?></span></th>
                <th class="col-cycle"><span><?= __('Duration') ?></span></th>
                <th class="col-promo last"><span><?= __('Discount') ?></span></th>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($block->getDiscounts())): ?>
                <?php foreach($block->getDiscounts() as $key => $discount): ?>
                    <tr class="<?php echo ($key % 2) ? 'even' : 'odd'?>">
                        <td class="col-product">
                            <div class="option-value"><?php echo $block->escapeHtml($discount['product']) ?></div>
                        </td>
                        <td class="col-cycle">
                            <div class="option-value"><?php echo $block->escapeHtml($block->getCycleLabel($discount['cycles'])) ?></div>
                        </td>
                        <td class="col-promo last">
                            <div class="price-excl-tax">
                                <div class="price">R$ <?php echo $block->escapeHtml($discount['amount']) ?></div>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="empty"><span><?= __('No discounts found.') ?></span></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Payment Method') ?></span>
    </div>
    <?php if (!empty($subscription)): ?>
        <?php if ($subscription->getData('payment_method') == PaymentMethod::CREDIT_CARD || $subscription->getData('payment_method') == PaymentMethod::DEBIT_CARD) : ?>
            <div>
                <div class="paymentProfiles-list">
                    <table>
                        <thead>
                        <tr>
                            <th><?= __('Card') ?></th>
                            <th><?= __('Holder Name') ?></th>
                            <th><?= __('Action') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($block->getFilteredPaymentProfiles() as $key => $profile): ?>
                            <tr class="<?php echo ($key % 2) ? 'even' : 'odd'?>">
                                <td>
                                    <img class="card-icon" src="<?= $block->getViewFileUrl('Vindi_Payment::images/cc') . '/' . $block->getCreditCardImage($profile->getCcType()) ?>" alt="<?= $block->escapeHtmlAttr($profile->getCcType()) ?>">&nbsp;&nbsp;&nbsp;
                                    <span><?= $profile->getCcType() . '****' . $block->escapeHtml($profile->getCcLast4()) ?></span>
                                </td>
                                <td>
                                    <?= $block->escapeHtml($profile->getCcName()) ?>
                                </td>
                                <td>
                                    <a href="<?= $block->getUrl('vindi_vr/subscription/editpayment', ['id' => $block->getRequest()->getParam('id')]) ?>"><?= __('Edit method') ?></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php else : ?>
            <div class="admin__page-section-content">
                <table class="admin__table-secondary">
                    <tbody>
                    <tr class="even">
                        <td class="col-product non-card-method-image-container">
                            <div class="non-card-method-image"><?= $block->getPaymentMethodImage() ?></div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <div class="admin__page-section-content">
            <p class="empty"><span><?= __('No payment methods found.') ?></span></p>
        </div>
    <?php endif; ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Billings') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary">
            <thead>
            <tr class="headings">
                <th class="col-order-id"><?= __('ID') ?></th>
                <th class="col-increment-id"><?= __('Order ID') ?></th>
                <th class="col-created-at"><?= __('Created at') ?></th>
                <th class="col-total"><?= __('Total') ?></th>
                <th class="col-status"><?= __('Status') ?></th>
                <th class="col-view"><?= __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getLinkedOrders() as $order): ?>
                <tr>
                    <td><?= $block->escapeHtml($order['order_id']); ?></td>
                    <td><?= $block->escapeHtml($order['increment_id']); ?></td>
                    <td><?= $block->escapeHtml((new IntlDateFormatter('pt_BR', IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE))->format(new DateTime($order['created_at']))); ?></td>
                    <td><?= $block->escapeHtml($block->formatPrice($order['total'])); ?></td>
                    <td><?= $block->escapeHtml($block->getOrderStatusLabel($order['status'])); ?></td>
                    <td><a href="<?= $block->getUrl('sales/order/view', ['order_id' => $order['order_id']]); ?>"><?= __('View') ?></a></td>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($block->getLinkedOrders())): ?>
                <tr>
                    <td colspan="6" class="empty"><span><?= __('No orders found.') ?></span></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</section>

<?php if (!empty($block->getLinkedOrders())): ?>
    <?php
    $linkedOrders = $block->getLinkedOrders();
    $lastOrder = end($linkedOrders);
    $shippingAddress = $block->getShippingAddress();
    ?>
    <?php if ($shippingAddress): ?>
        <div class="admin__page-section-title">
            <span class="title"><?= __('Shipping Address') ?></span>
        </div>
        <hr class="divider">
        <div class="address">
            <div>
                <p class="label"><?= __('Information') ?></p>
                <?php
                $streetArray = $shippingAddress->getStreet();
                $street = isset($streetArray[0]) ? $streetArray[0] : '';
                $number = isset($streetArray[1]) ? $streetArray[1] : '';
                $complement = isset($streetArray[2]) ? $streetArray[2] : '';
                $neighborhood = isset($streetArray[3]) ? $streetArray[3] : '';
                ?>
                <p><?php echo $block->escapeHtml($shippingAddress->getFirstname() . ' ' . $shippingAddress->getLastname()) ?></p>
                <?php if ($street || $number): ?>
                    <p><?php echo $block->escapeHtml(trim("$street, $number")) ?></p>
                <?php endif; ?>
                <?php if ($complement): ?>
                    <p><?php echo $block->escapeHtml($complement) ?></p>
                <?php endif; ?>
                <?php if ($neighborhood): ?>
                    <p><?php echo $block->escapeHtml($neighborhood) ?></p>
                <?php endif; ?>
                <p><?php echo $block->escapeHtml($shippingAddress->getCity() . ', ' . $shippingAddress->getRegion()->getRegionCode() . ', ' . $shippingAddress->getPostcode()) ?></p>
                <p><?php echo $block->escapeHtml($shippingAddress->getCountryId()) ?></p>
                <p>T: <?php echo $block->escapeHtml($shippingAddress->getTelephone()) ?></p>
            </div>
            <!-- <a href="#" class="text-blue">--><?php //= __('Edit Address') ?><!--</a>-->
        </div>
    <?php endif; ?>
<?php endif; ?>

<div class="flex">
    <button class="button" id="cancel-subscription-button">Cancelar assinatura</button>
</div>

<?php $cancelSubscriptionButtonMessage = __('Are you sure you want to cancel your subscription?'); ?>
<?php $cancelSubscriptionUrl = 'vindi_vr/subscription/cancelsubscription/id/' . $block->getSubscriptionId() ?>
<script type="text/javascript">
    require(['jquery', 'mage/url', 'mage/translate'], function($, url) {
        $('#cancel-subscription-button').on('click', function() {
            if (confirm($.mage.__("<?php echo $cancelSubscriptionButtonMessage ?>"))) {
                window.location.href = url.build("<?php echo $cancelSubscriptionUrl ?>");
            }
        });

        function handleBackButton() {
            var previousPage = document.referrer;
            var subscriptionIndexUrl = url.build('vindi_vr/subscription/index');
            if (previousPage.includes('vindi_vr/subscription/index')) {
                history.back();
            } else {
                window.location.href = subscriptionIndexUrl;
            }
        }

        $('#custom-back-button, #bottom-back-button').on('click', handleBackButton);
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var subscriptionsElement = document.querySelector('.minhas-assinaturas, .my-subscriptions');

        if (subscriptionsElement) {
            var currentLi = subscriptionsElement.closest('li');

            if (currentLi) {
                currentLi.classList.add('current');
            }
        }
    });
</script>
<br>
<div class="back-button-container">
    <button type="button" id="bottom-back-button" class="back-button"><?= __('< Back') ?></button>
</div>
