<?php if ($this->canShowBankSlipPix()) : ?>
    <div class="checkout-success qr-code">
        <p>
            <?= $block->getInfoMessageOnepageSuccess() ?>
        </p>
        <object data="<?= $block->getQrCodePix() ?>" type="image/svg+xml" class="qr-code" id="qrcode">
            <button
                id="vindi-pix-button-open"
                type="button"
                class="action primary checkout"
                title="Open QR Code Pix"
                onclick="window.open('<?= $block->getQrCodePix() ?>', '_blank')">
                <?php echo __('Open QR Code') ?>
            </button>
        </object>
        <p style="word-break: break-all;"><?= $block->getQrcodeOriginalPath() ?></p>

        <div data-bind="scope: 'vindiPix'" class="box-qr">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
        <div id="copied-success" class="copied" style="display: none">
            <span><?= __('QR Code Key copied') ?></span>
        </div>

        <div class="container-button-print">
            <button
                id="vindi-bankslip-button-print"
                type="button"
                class="action primary checkout"
                title="Print Vindi Bankslip"
                onclick="window.open('<?php echo $block->getBankslipPrintUrl() ?>', '_blank')"
            >
                <?php echo __('Print your Bankslip') ?>
            </button>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "vindiPix": {
                            "component": "Vindi_Payment/js/view/onepage/vindi-pix",
                            "qrCodeKey": <?= $block->getQrcodeOriginalPath() ?>
                        }
                    }
                }
            }
        }
    </script>

<?php endif; ?>
