<?php

use Vindi\Payment\Block\Onepage\Pix;

/** @var $block Pix */
?>

<?php if ($block->canShowPix()) : ?>
    <div class="checkout-success">
        <p>
            <?= $block->getInfoMessageOnepageSuccess() ?>
        </p>
        <object data="<?= $block->getQrCodePix() ?>" type="image/svg+xml" class="qr-code" id="qrcode">
            <p>
                <?= $block->getQrCodeWarningMessage() ?>
            </p>
            <button
                id="vindi-pix-button-open"
                type="button"
                class="action primary checkout"
                title="Open QR Code Pix"
                onclick="window.open('<?= $block->getQrCodePix() ?>', '_blank')">
                <?php echo __('Open QR Code') ?>
            </button>
        </object>

        <div data-bind="scope: 'vindiPix'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "vindiPix": {
                            "component": "Vindi_Payment/js/view/onepage/vindi-pix",
                            "qrCodeKey": <?= $block->getQrcodeOriginalPath() ?>
                        }
                    }
                }
            }
        }
    </script>

<?php endif; ?>
