<?php

/**
 * @var Vindi\Payment\Block\Adminhtml\Order\LinkField $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>
<?php if (str_contains($block->getPaymentMethod(), $block::VINDI_PAYMENT_LINK)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
        <span class="title">
              <?php /* @escapeNotVerified */ echo __('Payment Link') ?>
        </span>
        </div>
        <div class="admin__page-section-item-content edit-checkoutfield-date"
             style="display: flex;flex-direction: row;flex-wrap: nowrap;align-items: center;"
             id="edit-checkoutfield-info-form">

            <?php if ($block->isLinkPaid()): ?>
                <div>
                    <span>
                        <?php /* @escapeNotVerified */ echo __('The payment link has already been processed.') ?>
                    </span>
                </div>
            <?php else: ?>

                <fieldset class="admin__fieldset" style="display: <?= !$block->getPaymentLink() || $block->isLinkExpired() ? 'none' : 'block' ?>">
                    <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
                    <input type="hidden" id="orderid" value="<?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $request = $objectManager->get('Magento\Framework\App\Request\Http');
                    echo $param = $request->getParam('order_id'); ?>"/>

                    <span class="link" style="display: none"><?= $block->getPaymentLink(); ?></span>
                </fieldset>

                <button id="vind_payment_send" class="action-default action-secondary action-send">
                    <?php /* @escapeNotVerified */ echo __('Create and send new payment link') ?>
                </button>
            <?php endif; ?>
        </div>
    </section>

    <script type="text/javascript">
        require([
            'jquery',
            'loader',
            'domReady!',
            'mage/validation',
            'mage/translate',
            'jquery/ui'
        ], function ($) {
            $("#vind_payment_send").click(function() {
                $('#loader-example').trigger('processStart');

                var orderId = $('#orderid').val();
                var formKey = $('input[name="form_key"]').val();
                var url = '<?= /** @noEscape */ $block->getUrl("vindi_payment/paymentlink/send")?>';

                $(document.body).trigger('processStart');

                $.ajax({
                    url: url,
                    data: {
                        order_id: orderId,
                        form_key: formKey
                    },
                    type: "POST",
                }).always(function () {
                    $(document.body).trigger('processStop');
                    location.reload();
                });

            });
        });
    </script>
<?php endif ?>
