<?php

use Vindi\Payment\Block\Adminhtml\Subscription\View;

/** @var View $block */

$block->checkAndSaveSubscriptionItems();
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Details') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                    <tr>
                        <th><?= __('Customer') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getCustomerName()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Status') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getStatus())) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Since') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getStartAt()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Plan') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getPlanName()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Periodicity') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getPlanCycle())) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Duration') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getPlanDuration())) ?></strong></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Billing') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody>
                    <tr>
                        <th><?= __('Next Billing') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getNextBillingAt()) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Billing') ?></th>
                        <td><strong><?php echo $block->escapeHtml(__($block->getBillingTrigger())) ?></strong></td>
                    </tr>
                    <tr>
                        <th><?= __('Payment Method') ?></th>
                        <td><strong><?php echo $block->escapeHtml($block->getPaymentMethod()) ?></strong></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Products') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th class="col-product"><span><?= __('Product') ?></span></th>
                <th class="col-qty"><span><?= __('Quantity') ?></span></th>
                <th class="col-cycle"><span><?= __('Duration') ?></span></th>
                <th class="col-price"><span><?= __('Price') ?></span></th>
                <th class="col-status last"><span><?= __('Status') ?></span></th>
            </tr>
            </thead>
            <?php if (!empty($block->getProducts())): ?>
                <?php foreach($block->getProducts() as $key => $product): ?>
                    <tbody class="<?php echo ($key%2) ? 'even' : 'odd'?>">
                    <tr class="border">
                        <td class="col-product">
                            <div class="option-value"><?php echo $block->escapeHtml($product['product']['name']) ?></div>
                        </td>
                        <td class="col-qty">
                            <div class="option-value"><?php echo $block->escapeHtml($product['quantity']) ?></div>
                        </td>
                        <td class="col-cycle">
                            <div class="option-value"><?php echo $block->escapeHtml($block->getCycleLabel($product['cycles'])) ?></div>
                        </td>
                        <td class="col-price">
                            <div class="price-excl-tax">
                                <div class="price"><?php echo $block->escapeHtml($product['pricing_schema']['short_format']) ?></div>
                            </div>
                        </td>
                        <td class="col-status last">
                            <div class="option-value"><?php echo $block->escapeHtml(__($product['status'])) ?></div>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
            <?php endif; ?>
        </table>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Periods') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th class="col-product"><span><?= __('Period') ?></span></th>
                <th class="col-billing_at"><span><?= __('Billing') ?></span></th>
                <th class="col-cycle last"><span><?= __('Cycle') ?></span></th>
            </tr>
            </thead>
            <?php if (!empty($block->getPeriods())): ?>
                <?php foreach($block->getPeriods() as $key => $period): ?>
                    <tbody class="<?php echo ($key%2) ? 'even' : 'odd'?>">
                    <tr class="border">
                        <td class="col-product">
                            <div class="option-value"><?php echo $block->escapeHtml($block->dateFormat($period['start_at'])) ?> - <?php echo $block->escapeHtml($block->dateFormat($period['end_at'])) ?></div>
                        </td>
                        <td class="col-billing_at">
                            <div class="option-value"><?php echo $block->escapeHtml($block->dateFormat($period['billing_at'])) ?></div>
                        </td>
                        <td class="col-cycle">
                            <div class="option-value"><?php echo $block->escapeHtml($period['cycle']) ?></div>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
            <?php endif; ?>
        </table>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Discounts') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th class="col-product"><span><?= __('Product') ?></span></th>
                <th class="col-cycle"><span><?= __('Duration') ?></span></th>
                <th class="col-promo last"><span><?= __('Discount') ?></span></th>
            </tr>
            </thead>
            <?php if (!empty($block->getDiscounts())): ?>
                <?php foreach($block->getDiscounts() as $key => $discount): ?>
                    <tbody class="<?php echo ($key%2) ? 'even' : 'odd'?>">
                    <tr class="border">
                        <td class="col-product">
                            <div class="option-value"><?php echo $block->escapeHtml($discount['product']) ?></div>
                        </td>
                        <td class="col-cycle">
                            <div class="option-value"><?php echo $block->escapeHtml($block->getCycleLabel($discount['cycles'])) ?></div>
                        </td>
                        <td class="col-promo last">
                            <div class="price-excl-tax">
                                <div class="price">R$ <?php echo $block->escapeHtml($discount['amount']) ?></div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
            <?php endif; ?>
        </table>
    </div>
</section>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Orders') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary">
            <thead>
            <tr class="headings">
                <th class="col-order-id"><?= __('ID') ?></th>
                <th class="col-increment-id"><?= __('Order ID') ?></th>
                <th class="col-created-at"><?= __('Created At') ?></th>
                <th class="col-total"><?= __('Total') ?></th>
                <th class="col-status"><?= __('Status') ?></th>
                <th class="col-view"><?= __('View') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getLinkedOrders() as $order): ?>
                <tr>
                    <td><?= $block->escapeHtml($order['order_id']); ?></td>
                    <td><?= $block->escapeHtml($order['increment_id']); ?></td>
                    <td><?= $block->escapeHtml((new IntlDateFormatter('pt_BR', IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE))->format(new DateTime($order['created_at']))); ?></td>
                    <td><?= $block->escapeHtml($block->formatPrice($order['total'])); ?></td>
                    <td><?= $block->escapeHtml($order['status']); ?></td>
                    <td><a href="<?= $block->getUrl('sales/order/view', ['order_id' => $order['order_id']]); ?>"><?= __('View') ?></a></td>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($block->getLinkedOrders())): ?>
                <tr>
                    <td colspan="6" class="empty"><span><?= __('No orders found.') ?></span></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</section>
