<?php if ($block->canShowBankslipInfo()) : ?>
    <dl class="payment-method">
        <dt class="title"><strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></strong></dt>
        <dd class="content">
            <br/>
            <p><?php echo sprintf(__('Print Url: %s'), '<a target="_blank" href="'. $block->getPrintUrl() . '">'. $block->getPrintUrl() . '</a>') ?></p>
            <br/>
        </dd>
    </dl>
<?php endif; ?>