<?php

use Vindi\Payment\Block\Info\BankSlipPix;

/** @var $block BankSlipPix */
?>
<dl class="payment-method">
    <dt class="title"><strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></strong></dt>
    <?php if (!$block->hasInvoice() && $block->canShowBankSlipPixInfo()) : ?>
        <dd class="content">
            <?php if ($block->getQrCodePix()): ?>
                <object data="<?= $block->getQrCodePix() ?>" type="image/svg+xml" class="qr-code" id="qrcode" width="200" height="200">
                    <p>
                        <?= $block->getQrCodeWarningMessage() ?>
                    </p>
                    <button
                        id="vindi-pix-button-open"
                        type="button"
                        class="action primary checkout"
                        title="Open QR Code Pix"
                        onclick="window.open('<?= $block->getQrCodePix() ?>', '_blank')">
                        <?= __('Open QR Code') ?>
                    </button>
                </object>
            <?php endif; ?>
        </dd>
        <dd class="content">
            <br/>
            <p><?php echo sprintf(__('Print Url: %s'), '<a target="_blank" href="'. $block->getPrintUrl() . '">'. $block->getPrintUrl() . '</a>') ?></p>
            <br/>
        </dd>
    <?php endif; ?>
</dl>
