<?php

use Vindi\Payment\Block\Info\BankSlipPix;

/** @var $block BankSlipPix */
?>
<dl class="payment-method">
    <dt class="title"><strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></strong></dt>
    <?php if (!$block->hasInvoice() && $block->canShowBankSlipPixInfo()) : ?>
        <dd class="content">
            <br/>
            <p><?php echo sprintf(__('Print Url: %s'), '<a target="_blank" href="'. $block->getPrintUrl() . '">'. $block->getPrintUrl() . '</a>') ?></p>
            <br/>
        </dd>
    <?php endif; ?>
</dl>
